### ISSUE TITLE
Any way to disable flick for show()?

### ISSUE THREAD

**Issue by Eralyne** [octopitus/rn-sliding-up-panel#102]
### Issue Description

I am attempting to put multiple snapping points in my panel so that it can snap to the middle point, top point, or exit depending on if the user gestures upwards and downwards.

For the most part, my code works. However, when running show() to force slide the panel to a point I want it to sit at, it slides past that point if the velocity is great enough. When snapping from a small distance, it slides correctly. But, sliding from, say the top of the screen to the middle or from the bottom of the screen to the middle, it slides past the middle.

It seems that onDragEnd only tracks the panel position when the user stops dragging it and it does not really account the end position that the panel will be at after the flick occurs. Honestly, I can workaround this just fine if the flick could be disabled some way.

Things that I've tried to solve this issue:
- Tracking animatedValue and setting top draggableRange to different snap points based on midpoint reach
- Running show() twice sequentially? It shot it to the top of the draggableRange for some reason.
- Messing around with the friction, minimumVelocity, minimumDistance, allowMomentum values
- Rerunning show() when reaching near a snap point

I would really love either a way to disable flick for show() (as I think that's my problem) or some pointers towards the correct way for setting up multiple snapping points without having to fork and rewrite this component.

Thanks!

### Steps to Reproduce / Code Snippets / Screenshots
This is my dragEnd function code
```js                                                        
        // If panel was moving upwards, do upwards operations
        if (gestureState.vy < 0) {
          // If user moves the panel above middleUp, drag it to the top
          if (position >= this.draggableRange.middleUp) {
            this._panel.show(this.draggableRange.top)

          } else if (position >= this.draggableRange.middleBreak) {
            // If not above middleUp but is above middleBreak, drag it to middle
            this._panel.show(this.draggableRange.middle)

          } else {
            // Else, hide it
            this._panel.hide()
          }
        } else {
          // If panel was moving downwards, do downward operations
          if (position >= this.draggableRange.topBreak) {
            this._panel.show(this.draggableRange.top)

          } else if (position >= this.draggableRange.middleBreak) {

            this._panel.show(this.draggableRange.middle)
          } else {
            // Else, hide it
            this._panel.hide()
          }
        }
 ```

This is what my panel looks like
```js
        <SlidingUpPanel
            ref={c => this._panel = c}
            onDragEnd={(position, gestureState) => this.dragEnd(position, gestureState)}
            draggableRange={{ top: this.draggableRange.top, bottom: this.draggableRange.bottom }}
            onRequestClose={() => this._panel.hide()}
            allowMomentum={false}
            showBackdrop={false}
         >
```

My draggableRange values (I've attempted with static pixel values as well)
```js
this.draggableRange = {
      top: Metrics.screenHeight,
      topBreak: Metrics.screenHeight * 0.80,
      middleUp: Metrics.screenHeight * 0.45 + (Metrics.screenHeight * 0.45 * 0.20),
      middle: Metrics.screenHeight * 0.45,
      middleBreak: Metrics.screenHeight * 0.45) * 0.80,
      bottom: 0
    }
```

---
### Environment
* Version: 2.1.0
* React Native version: 0.57.3
* Platform(s) (iOS, Android, or both?): IOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by Eralyne** [comment]
I fixed my issue by tracking animatedValue position, subtracting it from the middlePoint that I want to snap to, and check if that subtracted absolute value is within a small range. If it is, I snap it to middlePoint. 

```js
_onAnimatedValueChange({ value }) {
    if (Math.abs(this.draggableRange.middle - Math.round(value)) <= 3) {
      this._panel.show(this.draggableRange.middle)
    }
  }
```

A component method that is called when panel stops moving would really be a great improvement.

**Comment by epurban** [comment]
This seems to still have problems. I have created an onpress function via a touchablewithoufeedback in the render method of the panel. When its called, it calls _panel.show(topPosition), but the panel often times does not reach the top position. Instead, it only goes halfway. Very frustrating.

**Comment by Eralyne** [comment]
@epurban  Could I see a code block of how you're trying to implement it?

**Comment by epurban** [comment]
> @epurban Could I see a code block of how you're trying to implement it?

Well sure, but I don't fully understand your "fix". I did not change the _onAnimatedValueChange function of the SlidingUpPanel. However, this is how I implement the onPress:

In SlidingUpPanel
`return (
      <Animated.View
        key="content"
        pointerEvents="box-none"
        style={animatedContainerStyles}
        {...this._panResponder.panHandlers}>
        <TouchableWithoutFeedback style={{ height: visibleHeight}} 
          onPress={() => this.onPanelPress()}>
          {this.props.children}
        </TouchableWithoutFeedback>
      </Animated.View>
    )

onPanelPress() {
    const {height} = Dimensions.get('screen');
    const animatedValue = this.props.animatedValue.__getValue();
    if (animatedValue === this.props.draggableRange.bottom) {
      this.show(height);
      this.props.onSwipeToTop();
    }
  }`

**Comment by Eralyne** [comment]
Okay, so my "fix" is incredibly important to make the snapping work. Also, this isn't a change in the SlidingUpPanel. My code is not a fork or anything. If you go [here](https://github.com/octopitus/rn-sliding-up-panel/issues/96#issuecomment-469560606), you'll see the way I implemented the _onAnimatedValueChange.

I think v2 has had some great changes wherein you don't really need to fork it to achieve this kind of stuff anymore. Previously with v1, I forked for snapping. I recommend you check out the linked solution along with my implementation of it to see exactly how you can setup snapping.

**Comment by epurban** [comment]
> Okay, so my "fix" is incredibly important to make the snapping work. Also, this isn't a change in the SlidingUpPanel. My code is not a fork or anything. If you go [here](https://github.com/octopitus/rn-sliding-up-panel/issues/96#issuecomment-469560606), you'll see the way I implemented the _onAnimatedValueChange.
> 
> I think v2 has had some great changes wherein you don't really need to fork it to achieve this kind of stuff anymore. Previously with v1, I forked for snapping. I recommend you check out the linked solution along with my implementation of it to see exactly how you can setup snapping.

Thank you! I will check it out when I get home from class. I am using this library for a school project and have to submit the app by this Sunday, so it's huge that I get this figured out. Thanks again!

**Comment by epurban** [comment]
Here is a video of my issue. I have two positions in my panel, the top and the bottom. When I click the panel (or drag and let go) when its in the bottom position, it should move all the way to the top in one fell swoop. However, it never seems to make it to the top! This is driving me nuts! I was using onDragEnd to check the positions and then call this._panel.show(TOP) as necessary, but I can't use your fix because it's not even close to within a few pixels from its target.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/22136514/55678760-e7f9ef00-58cc-11e9-9b8b-42907af575cf.gif)

**Comment by Eralyne** [comment]
Hey, could you please send me a snippet of all of your code that relates to panel show?
