### ISSUE TITLE
Panel isn't on top - zIndex issue

### ISSUE THREAD

**Issue by hoc-ht** [octopitus/rn-sliding-up-panel#179]
### Issue Description

I think there is a zIndex issue. I tried a very simple example, but it seems the Show Panel button is overlap the panel.

![image](https://user-images.githubusercontent.com/42890512/85200370-0ce75000-b321-11ea-8ac1-f86551afec55.png)

### Steps to Reproduce / Code Snippets / Screenshots

`import React from 'react';
import {View, Button, Text} from 'react-native';

import SlidingUpPanel from 'rn-sliding-up-panel';

const styles = {
  container: {
    flex: 1,
    backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: 'center'
  }
};

class MyComponent extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <Button title='Show panel' onPress={() => this._panel.show()} />
        <SlidingUpPanel ref={c => this._panel = c}>
          <View style={styles.container}>
            <Text>Here is the content inside panel</Text>
            <Button title='Hide' onPress={() => this._panel.hide()} />
          </View>
        </SlidingUpPanel>
      </View>
    )
  }
}

export default MyComponent;
`

---
### Environment
* Version: 2.4.2
* React Native version: 0.62.2
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator - Android 9

**Comment by octopitus** [comment]
Move the `<Button title='Show panel' onPress={() => this._panel.show()} />` to below the panel should fix the issue. The reason is `Button` component on Android has `elevation` which sometime mess up with zIndex.

**Comment by benjamindulau** [comment]
Same here. Moving the button below the panel doesn't resolve the issue. Other ideas? 🙄

**Comment by elmcapp** [comment]
Im having same issue. I have a card component that covering the panel.

I move components around a stated but does not help. This only happens on Android. Also I notice on android the sliding is not smooth when using this._panel. only smooth slide when using finger to slide. 

The main problem is that the slider is not on top when using with android
