### ISSUE TITLE
CurrentlyFocusedField is deprecated and will be removed in a future release. Use currentlyFocusedInput

### ISSUE THREAD

**Issue by B-Houssam** [octopitus/rn-sliding-up-panel#191]
### Issue Description

I'm using this package with a TextInput, but when the focus is on the TextInput (the keyboard appear)  it gives an error : 
`
currentlyFocusedField is deprecated and will be removed in a future release. Use currentlyFocusedInput`

---
### Environment
* Version: Latest
* React Native version: 0.63
* Platform(s) : Android
* Device info: Simulator and real device

**Comment by B-Houssam** [comment]
i found a solution for it 
you can open in the app project folder : 
node_modules/rn-sliding-up-panel/SlidingUpPanel.js 
and emove and replace the line **315** by the following:
 `const node = TextInput.State.currentlyFocusedInput() ? findNodeHandle(TextInput.State.currentlyFocusedInput()) : TextInput.State.currentlyFocusedField();`

**Comment by B-Houssam** [comment]
please update it to close the issue

**Comment by TomasSestak** [comment]
+1

**Comment by TomasSestak** [comment]
> please update it to close the issue

Can you make a pull request with the fix?

**Comment by B-Houssam** [comment]
it is fixed

**Comment by mwerder** [comment]
The fix doesn't seem to work for me, I updated to V2.4.4 and still have this issue

![IMG_5B9F696D5145-1](https://user-images.githubusercontent.com/16059443/99230083-2799f400-27ef-11eb-886a-ce3913721beb.jpeg)

**Comment by jrapala** [comment]
Seeing this issue as well on 2.4.4
