### ISSUE TITLE
onDragEnd is not called

### ISSUE THREAD

**Issue by andrycodestuffs** [octopitus/rn-sliding-up-panel#82]
### Issue Description
I'm using the following code to snap the panel to the bottom or the top based on panel position given after user finished to drag it (by using `onDragEnd`).
This is what I'm using:
```
snapOnDragEnd = (position) => {
    if (this.slidingUpPanelRef) {
      // Snap panel to bottom if height didn't reach half of the expanded panel max height
      if (position < (EXPANDEND_PANEL_MAX_HEIGHT / 2)) this.slidingUpPanelRef.transitionTo(COLLAPSED_PANEL_HEIGHT)

      // Otherwise snap to top
      else this.slidingUpPanelRef.transitionTo(EXPANDEND_PANEL_MAX_HEIGHT)
    }
  }
```
Later on in the render method
```
...
<SlidingUpPanel
  ref={ref => { this.slidingUpPanelRef = ref }}
  showBackdrop={true}
  ...other props
  onDragEnd={this.snapOnDragEnd}>
  ...children
</SlidingUpPanel>
```
But I have encountered a problem, `onDragEnd` is not called when a user swipes up to return to the home screen (e. g. with an iPhone X).
The result is a slightly opened panel that, combined with `showBackdrop={true}`, makes the UI unresponsive (since the panel it's still opened, even if slightly)

### Steps to Reproduce / Code Snippets / Screenshots
I have recorded a video to showcase the described issue using the XCode simulator running iPhone X on iOS 12.1: https://youtu.be/oFpJL_7ZCR4

---
### Environment
* Version: 1.3.1
* React Native version: 0.57.4
* Platform(s): iOS/Android
* Device info: Running on simulator

**Comment by octopitus** [comment]
Thanks @andrycodestuffs. Very detailed report. I've addressed your issue in v2. You may want to try (npm install rn-sliding-up-panel@next). 

Below is the implementation for v2:

```js
snapOnDragEnd = (position) => {
  if (this.slidingUpPanelRef) {
    // Snap panel to bottom if height didn't reach half of the expanded panel max height
    if (position < (EXPANDEND_PANEL_MAX_HEIGHT / 2)) this.slidingUpPanelRef.hide()

    // Otherwise snap to top
    else this.slidingUpPanelRef.show()
  }
}

<SlidingUpPanel
  ref={ref => { this.slidingUpPanelRef = ref }}
  onDragEnd={this.snapOnDragEnd}
  draggagleRange={{
    top: EXPANDEND_PANEL_MAX_HEIGHT,
    bottom: COLLAPSED_PANEL_HEIGHT
  }}>
  {/* children elements */}
</SlidingUpPanel>
```

**Comment by andrycodestuffs** [comment]
I noticed that the v2 `SlidingUpPanel` doesn't accept `allowDragging` as a prop.
How should #71 be solved then?

**Comment by andrycodestuffs** [comment]
I think that the README wasn't updated properly since `allowDragging` it's still present in the source code

**Comment by octopitus** [comment]
Oops. Thanks @andrycodestuffs. Lets me update the docs.
