### ISSUE TITLE
draggableRange top different on devices with/without soft menu bar

### ISSUE THREAD

**Issue by sinodko** [octopitus/rn-sliding-up-panel#87]
### Issue Description

There is an issue with device with/without bottom soft menu bar... when i set `draggableRange` to `{top: 200}`, it looks different on devices with soft menu bar and without soft menu bar. It should be definitely the same. It looks like the position of the `rn-sliding-up-panel` component is calculated based on some absolute bottom: 0 (without soft menu in mind) but I was not able to fix the issue on my own so I'm asking for a help. 

I've also tried to use [react-native-extra-dimensions-android](https://github.com/Sunhat/react-native-extra-dimensions-android) package to play with heights but nothing seems to work. I also tried to add 
 `position: "relative"` style to the upper view container and I hoped that position will be calculated with upper View container in mind but without any success. Thanks for any help!

### Steps to Reproduce / Code Snippets / Screenshots

device with soft menu bar (Emulator device): 
![nieco1](https://user-images.githubusercontent.com/33039909/51803924-dc4dd480-225a-11e9-9d5b-cea01a8207f3.png)

device without soft menu bar (Real device Xiaomi mi 8):
![nieco2](https://user-images.githubusercontent.com/33039909/51803929-e2dc4c00-225a-11e9-864b-06dd03f28519.png)

---
### Environment
* Version: v2 - next branch
* React Native version: 0.57.5
* Platform(s): Android
* Device info : Emulator + Xiaomi mi 8

**Comment by octopitus** [comment]
Thanks @sinodko. The position of the panel depends on the height of screen (`Dimensions.get('screen').height`). Maybe it's something related to [this issue](https://github.com/facebook/react-native/issues/4934).

**Comment by sinodko** [comment]
Dont you have any idea? :/

**Comment by octopitus** [comment]
@sinodko Will try to fix this issue within today.

**Comment by sinodko** [comment]
@octopitus thank you so much! hope you'll had more luck with it than I had!

**Comment by octopitus** [comment]
@sinodko I just released a fixed in version `v2.0.0-rc5`. Can help to check?

**Comment by sinodko** [comment]
@octopitus Thank you so much! it's closer but still not the same :/ enclosing the pictures
![real device xiaomi mi 8](https://user-images.githubusercontent.com/33039909/52125218-0bce5980-262c-11e9-92d3-82453330318b.png)

![emulator device](https://user-images.githubusercontent.com/33039909/52125226-0ffa7700-262c-11e9-817a-df8a0de49ca6.png)

**Comment by andrycodestuffs** [comment]
I found out a solution, may I edit the v2 branch code and submit a PR?

**Comment by andrycodestuffs** [comment]
My solution uses https://github.com/Sunhat/react-native-extra-dimensions-android, is this a problem?
(maybe you want to avoid linking native dependencies)

**Comment by andrycodestuffs** [comment]
A possible solution without using `react-native-extra-dimensions-android` as a `rn-sliding-up-panel` dependency:

```
// ... in the import section
import { Platform } from 'react-native'
import ExtraDimensions from 'react-native-extra-dimensions-android'

// ...

const SLIDING_UP_PANEL_HEIGHT = Platform.select({
  ios: Dimensions.get('screen').height,
  android: ExtraDimensions.get('REAL_WINDOW_HEIGHT')
})

// ... in the render method
<SlidingUpPanel
  // SlidingUpPanel props
  height={SLIDING_UP_PANEL_HEIGHT}>
  {/* SlidingUpPanel child */}
</SlidingUpPanel>
```

**Comment by sinodko** [comment]
@andrycodestuffs the result is exactly the same as I posted in my latest pictures above :/ I've tried to use rn-extra-dimensions-android package before but it didn't work. The problem is that package returns the height of the screen always with soft menu bars height, even if soft menu bar isn't visible at the time of render.

**Comment by andrycodestuffs** [comment]
I'm a bit confused, I retested `v2.0.0-rc5` and it now works for my device (an LG G4 with the navigation bar disabled) but on a Huawei P20 Pro the `PanelHeader` is hidden behind the navigation bar

**Comment by sinodko** [comment]
maybe we could try to find a way to determine if soft-menu is visible or not. Then based on result we can subtract soft_menu_height from total height. But it isn't that easy at all. I tried to find a native solution for that but didn't seems to work.

**Comment by andrycodestuffs** [comment]
If I receive the permission to use `react-native-extra-dimensions-android ` as a native dependency, I'll work on a solution (as I said earlier, maybe he is trying to avoid native dependency that needs to be linked)

**Comment by sinodko** [comment]
or we can just mask the overflowing part of panel with some nice design decoration to make it look like it is there on purpose 😄 😄

**Comment by andrycodestuffs** [comment]
Hey it's a feature, not a bug

**Comment by sinodko** [comment]
@octopitus  I can see google maps logo so I suggwest there is no map overflow but I will check it out and I let you know

**Comment by octopitus** [comment]
This seems like an issue with React Native itself (https://github.com/facebook/react-native/issues/14887). It can not determine the dimensions changed (Caused by the soft menu bar is hidden). The position of panel totally depends on the height of screen (`Dimensions.get('screen').height`).

Related:
- [Determine whether hardware buttons are drawn on screen in React Native
](https://stackoverflow.com/questions/44676208/determine-whether-hardware-buttons-are-drawn-on-screen-in-react-native)
- https://github.com/facebook/react-native/pull/20999

One more thing is, both `react-native-extra-dimensions-android` and `Dimensions.get('screen')` are likely using the same logic. So:

```js
Dimensions.get("screen").height == require("react-native-extra-dimensions-android").get("REAL_WINDOW_HEIGHT")
```

**Comment by andrycodestuffs** [comment]
@octopitus Unfortunately, I don't have any PRs that can fix this issue since what I tried used `react-native-extra-dimensions-android` (which didn't work out).
I'll let you know if I find any solution (I may not be able to fix this, as you said the issue lies in `react-native` itself)

**Comment by octopitus** [comment]
Thanks @andrycodestuffs. Anw, I'll keep this issue open for feature reference.

**Comment by dautent** [comment]
@sinodko 
看起来好像是小米等设备全面屏的问题（如果你打开这台xiaomi 8 的底部虚拟导航栏发现底部白色区域没有了那就是这个问题）
可以尝试将[这里](https://github.com/octopitus/rn-sliding-up-panel/blob/62dc4da155b6a4333d7461769e96d5d1b331954d/SlidingUpPanel.js#L335)做如下修改
```javascript
  const animatedContainerStyles = [
      styles.animatedContainer,
      //transform,
      { height, /*top: visibleHeight*/ bottom }
    ]
```

如果奏效，打开过渡动画，会发现位置有点点问题，继续将[这里](https://github.com/octopitus/rn-sliding-up-panel/blob/62dc4da155b6a4333d7461769e96d5d1b331954d/SlidingUpPanel.js#L327)做如下修改
```javascript
    const translateY = this._translateYAnimation.interpolate({
      inputRange: [-top, bottom, ],
      outputRange: [0,  top, ],
      extrapolate: 'clamp'
    })
```

希望对你有帮助

**Comment by andrycodestuffs** [comment]
I'm sorry but I do not understand your language and Google Translate isn't always that accurate 😅, have you found out a fix for this issue?

**Comment by sinodko** [comment]
@andrycodestuffs same here :/

**Comment by sinodko** [comment]
any updates on this one? I found the same issue on ios when i compare iphone X/XS/XR with older iphone devices.

**Comment by alexandrius** [comment]
This is config which works for me on every device.
I tried multiple ways some ways worked only on iOS (Android never rendered because it was offscreen)
```
    const translateY = this.props.animatedValue.interpolate({
      inputRange: [bottom, top],
      outputRange: [bottom, 0],
      extrapolate: 'clamp'
    })

    const transform = {transform: [{translateY}]}

    const animatedContainerStyles = [
      styles.animatedContainer,
      transform,
      {height, bottom: 0}
    ]
```

**Comment by sinodko** [comment]
@alexandrius if this is universal solution maybe we should just add it to the master. What do you think @octopitus ? I will try it this afternoon

**Comment by octopitus** [comment]
The solution of @alexandrius won't work.

Let's say you have draggableRange is `{top: 360, bottom: 0}`, apply the code above we will have the outputRange is `[0, 0]` which means the panel always stays at bottom position and cannot move. You can try yourself by replacing these lines: https://github.com/octopitus/rn-sliding-up-panel/blob/250fbd7d58ee927aa1d716b1b026613c0dd0ca23/SlidingUpPanel.js#L361-L373
with that pieces of code.

I already have the solution (on branch `android-dimensions-issue`) but still need more time to verify. Can try with:

```
yarn add https://github.com/octopitus/rn-sliding-up-panel.git#android-dimensions-issue
```

**Comment by sinodko** [comment]
@octopitus surprisingly, the solution by @alexandrius works :D I just needed to make some small changes with SlidingUpPanel and it works. Here is the code that I'm using:

```
<SlidingUpPanel
        showBackdrop={false}
        ref={panelRef}
        height={100}
        draggableRange={{ top: 180, bottom: 100 }}
        minimumDistanceThreshold={2}
      >
```

But I can clearly see that this is hack not a solution. I will now try your solution and I will let you know :)

**Comment by sinodko** [comment]
@octopitus your branch works! I'm so grateful and happy to see that you're making progress :) And excited about having this in master in a near future 💯🚀

**Comment by alexandrius** [comment]
My solution works but range values need to be changed as well.

**Comment by sinodko** [comment]
@alexandrius thumbs up 👍

@octopitus I can confirm that branch is working on iPhones X(simulator), 7 (simulator), XR (real device) xiaomi mi 8 (real device) and Nexus 5 (emulator)

**Comment by octopitus** [comment]
Thanks. Lets me merge the code and release new version.

**Comment by octopitus** [comment]
@sinodko @alexandrius Check out v2.1.1

**Comment by alexandrius** [comment]
@octopitus Thanks for the update I switched to my own sliding library though
